### ISSUE TITLE
`go.` considered bullet point

### ISSUE THREAD

**Issue by avidseeker** [bullets-vim/bullets.vim#152]
```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr. We've got a long way to
go. Lorem ipsum dolor sit amet,<cursor>
```
Hitting enter at <cursor> location results in:

```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr. We've got a long way to
a. Lorem ipsum dolor sit amet,
b. 
```

**Comment by harshad1** [comment]
Determining what is and is not a bullet is a heuristic. 

IMO If you are going to manually wrap lines this kind of issue is unavoidable.

One way around this would be to allow a user to disable alphabetical bullets (and any other bullet type if required).

**Comment by avidseeker** [comment]
> This kind of issue is unavoidable

If I'm using sentences that end at a single letter, that might be true. But that's not usually the case.

Why is "go" considered a bullet point anyways?

**Comment by harshad1** [comment]
Jul 19, 2024 16:16:11 avidseeker ***@***.***>:

**Comment by avidseeker** [comment]
How usual having +26 entries in alphabetic list? Is it even a commonmark standard?

It makes more sense disabling `aa.` entries.

**Comment by harshad1** [comment]
Lettered lists are not supported by markdown at all :)

So our options are:

1. Add an option to disable letters entirely (I like this)
2. Add an option to specify a maximum letter number

Anything else?

**Comment by avidseeker** [comment]
If option2 is implemented, then option1 is as easy as setting max_letter_num=0

**Comment by harshad1** [comment]
Please see #153 

Turns out we already have g:bullets_max_alpha_characters

Set it to 0 to disable alphabetical lists

**Comment by harshad1** [comment]
In conclusion

let g:bullets_max_alpha_characters = 1
let g:bullets_enable_roman_list = 0
